import type { Metadata } from "next";
import { Barlow, Urbanist } from "next/font/google";
import "./globals.css";

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["800", "700", "600"],
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  weight: ["800", "700", "600"],
});

export const metadata: Metadata = {
  title: "Clink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${barlow.variable} ${urbanist.variable} antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
